"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-08-03 04:45:09.144618+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# Revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "suite",
            sa.Enum(
                "INTENT",
                "RAG",
                "WORKFLOW",
                "FAULT",
                "LOAD",
                "REAL_MODEL",
                name="evaluation_suite",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("dataset", sa.String(length=255), nullable=False),
        sa.Column("dataset_version", sa.String(length=128), nullable=False),
        sa.Column("code_revision", sa.String(length=64), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("adapter_version", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=128), nullable=True),
        sa.Column("retrieval_version", sa.String(length=128), nullable=True),
        sa.Column("environment", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="evaluation_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("report_path", sa.String(length=1000), nullable=True),
        sa.CheckConstraint(
            "error_count >= 0", name=op.f("ck_evaluation_runs_evaluation_error_nonnegative")
        ),
        sa.CheckConstraint(
            "sample_count >= 0", name=op.f("ck_evaluation_runs_evaluation_sample_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_index(
        "ix_evaluation_runs_suite_started", "evaluation_runs", ["suite", "started_at"], unique=False
    )
    op.create_table(
        "inbox_messages",
        sa.Column("consumer_group", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "DONE",
                "DEAD",
                name="inbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("local_resource_type", sa.String(length=64), nullable=True),
        sa.Column("local_resource_id", sa.String(length=128), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_summary", sa.String(length=500), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_inbox_messages_inbox_attempt_nonnegative")
        ),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_inbox_messages_inbox_schema_version_positive")
        ),
        sa.PrimaryKeyConstraint("consumer_group", "message_id", name=op.f("pk_inbox_messages")),
    )
    op.create_index("ix_inbox_processing", "inbox_messages", ["status", "updated_at"], unique=False)
    op.create_table(
        "operation_ledger",
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("scope_type", sa.String(length=64), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("operation_type", sa.String(length=128), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CLAIMED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED_RETRYABLE",
                "FAILED_TERMINAL",
                "UNKNOWN",
                name="operation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_summary", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_operation_ledger_operation_attempt_nonnegative")
        ),
        sa.PrimaryKeyConstraint("operation_id", name=op.f("pk_operation_ledger")),
        sa.UniqueConstraint(
            "scope_type",
            "scope_id",
            "operation_type",
            "operation_id",
            name="uq_operation_scope_identity",
        ),
    )
    op.create_index(
        "ix_operation_ledger_status_lease",
        "operation_ledger",
        ["status", "lease_until"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "code",
            sa.Enum(
                "EMPLOYEE",
                "OPERATOR",
                "APPROVER",
                "ADMIN",
                name="role_code",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "DISABLED", name="team_status", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "char_length(code) BETWEEN 2 AND 64", name=op.f("ck_teams_team_code_length")
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 100", name=op.f("ck_teams_team_name_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("trace_context", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENDING",
                "SENT",
                "DEAD",
                name="outbox_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("broker_receipt", sa.String(length=500), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_outbox_events_outbox_attempt_nonnegative")
        ),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_outbox_events_outbox_schema_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation_ledger.operation_id"],
            name=op.f("fk_outbox_events_operation_id_operation_ledger"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("message_id", name=op.f("uq_outbox_events_message_id")),
    )
    op.create_index(
        "ix_outbox_aggregate", "outbox_events", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        "ix_outbox_due", "outbox_events", ["status", "next_attempt_at", "lease_until"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DISABLED",
                "LOCKED",
                name="user_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("acl_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("acl_version >= 1", name=op.f("ck_users_acl_version_positive")),
        sa.CheckConstraint(
            "char_length(display_name) BETWEEN 1 AND 100", name=op.f("ck_users_display_name_length")
        ),
        sa.CheckConstraint(
            "char_length(username) BETWEEN 3 AND 64", name=op.f("ck_users_username_length")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_users_team_id_teams"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index("ix_users_team_status", "users", ["team_id", "status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_location", sa.String(length=1000), nullable=False),
        sa.Column("owner_team_id", sa.String(length=36), nullable=True),
        sa.Column(
            "visibility_mode",
            sa.Enum(
                "PUBLIC",
                "ROLE",
                "TEAM",
                "EXPLICIT",
                name="document_visibility",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("active_version_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "ARCHIVED",
                name="document_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 300", name=op.f("ck_documents_document_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["active_version_id"],
            ["document_versions.id"],
            name="fk_documents_active_version",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_documents_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_team_id"],
            ["teams.id"],
            name=op.f("fk_documents_owner_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        "ix_documents_scope_status",
        "documents",
        ["visibility_mode", "owner_team_id", "status"],
        unique=False,
    )
    op.create_table(
        "login_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_family_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "REVOKED",
                "EXPIRED",
                name="login_session_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_sessions")),
    )
    op.create_index("ix_login_sessions_expiry", "login_sessions", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_login_sessions_token_family_id"),
        "login_sessions",
        ["token_family_id"],
        unique=False,
    )
    op.create_index(
        "ix_login_sessions_user_status", "login_sessions", ["user_id", "status"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "P1",
                "P2",
                "P3",
                "P4",
                name="ticket_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "RESOLVED",
                "CLOSED",
                "CANCELLED",
                name="ticket_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("assigned_team_id", sa.String(length=36), nullable=True),
        sa.Column("assignee_user_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sla_deadline", sa.DateTime(), nullable=True),
        sa.Column("sla_version", sa.Integer(), nullable=False),
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "char_length(description) BETWEEN 1 AND 10000",
            name=op.f("ck_tickets_ticket_description_length"),
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_tickets_ticket_title_length")
        ),
        sa.CheckConstraint(
            "escalation_level >= 0", name=op.f("ck_tickets_ticket_escalation_nonnegative")
        ),
        sa.CheckConstraint(
            "sla_version >= 0", name=op.f("ck_tickets_ticket_sla_version_nonnegative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tickets_ticket_version_positive")),
        sa.ForeignKeyConstraint(
            ["assigned_team_id"],
            ["teams.id"],
            name=op.f("fk_tickets_assigned_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_tickets_assignee_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_tickets_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("key", name=op.f("uq_tickets_key")),
    )
    op.create_index(
        "ix_tickets_creator_status", "tickets", ["created_by_user_id", "status"], unique=False
    )
    op.create_index("ix_tickets_sla_due", "tickets", ["status", "sla_deadline"], unique=False)
    op.create_index(
        "ix_tickets_team_status", "tickets", ["assigned_team_id", "status"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "document_acl_grants",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column(
            "principal_type",
            sa.Enum(
                "ROLE",
                "TEAM",
                "USER",
                name="document_acl_principal_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("principal_id", sa.String(length=36), nullable=False),
        sa.Column("granted_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_acl_grants_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_document_acl_grants_granted_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "document_id", "principal_type", "principal_id", name=op.f("pk_document_acl_grants")
        ),
        sa.UniqueConstraint(
            "document_id", "principal_type", "principal_id", name="uq_document_acl_principal"
        ),
    )
    op.create_index(
        "ix_document_acl_principal",
        "document_acl_grants",
        ["principal_type", "principal_id"],
        unique=False,
    )
    op.create_table(
        "document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("source_location", sa.String(length=1000), nullable=False),
        sa.Column("normalized_text", mysql.LONGTEXT(), nullable=True),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("chunker_version", sa.String(length=64), nullable=False),
        sa.Column("embedding_version", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REGISTERED",
                "QUEUED",
                "PARSING",
                "INDEXING",
                "READY",
                "FAILED",
                "SUPERSEDED",
                name="document_version_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("failure_stage", sa.String(length=64), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_summary", sa.String(length=500), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("segment_count", sa.Integer(), nullable=True),
        sa.Column("token_estimate", sa.Integer(), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("parsing_started_at", sa.DateTime(), nullable=True),
        sa.Column("indexing_started_at", sa.DateTime(), nullable=True),
        sa.Column("ready_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 1",
            name=op.f("ck_document_versions_document_version_attempt_positive"),
        ),
        sa.CheckConstraint(
            "page_count IS NULL OR page_count >= 0",
            name=op.f("ck_document_versions_document_page_nonnegative"),
        ),
        sa.CheckConstraint(
            "segment_count IS NULL OR segment_count >= 0",
            name=op.f("ck_document_versions_document_segment_nonnegative"),
        ),
        sa.CheckConstraint(
            "token_estimate IS NULL OR token_estimate >= 0",
            name=op.f("ck_document_versions_document_token_nonnegative"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_document_versions_document_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("document_id", "version", name="uq_document_versions_document_version"),
    )
    op.create_index(
        "ix_document_versions_status", "document_versions", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "ticket_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=True),
        sa.Column("before_summary", sa.JSON(), nullable=True),
        sa.Column("after_summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "ticket_version >= 1", name=op.f("ck_ticket_events_ticket_event_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_ticket_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation_ledger.operation_id"],
            name=op.f("fk_ticket_events_operation_id_operation_ledger"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_ticket_events_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticket_events")),
        sa.UniqueConstraint(
            "ticket_id", "operation_id", "event_type", name="uq_ticket_event_operation_type"
        ),
    )
    op.create_index(
        "ix_ticket_events_timeline",
        "ticket_events",
        ["ticket_id", "ticket_version", "created_at"],
        unique=False,
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("original_request", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "CLARIFYING",
                "PLANNED",
                "RUNNING",
                "WAITING_APPROVAL",
                "WAITING_RETRY",
                "CANCEL_REQUESTED",
                "NEEDS_REVIEW",
                "SUCCEEDED",
                "FAILED",
                "REJECTED",
                "CANCELLED",
                "EXPIRED",
                name="workflow_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("plan_id", sa.String(length=36), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(), nullable=True),
        sa.Column("pending_approval_id", sa.String(length=36), nullable=True),
        sa.Column("last_operation_id", sa.String(length=36), nullable=True),
        sa.Column("last_confirmed_stage", sa.String(length=128), nullable=True),
        sa.Column("active_run_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "plan_version >= 0", name=op.f("ck_workflows_workflow_plan_version_nonnegative")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workflows_workflow_version_positive")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_workflows_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pending_approval_id"],
            ["approvals.id"],
            name="fk_workflows_pending_approval",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version"],
            ["workflow_plans.id", "workflow_plans.version"],
            name="fk_workflows_current_plan",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["login_sessions.id"],
            name=op.f("fk_workflows_session_id_login_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_workflows_thread_id")),
    )
    op.create_index(
        "ix_workflows_owner_status", "workflows", ["owner_user_id", "status"], unique=False
    )
    op.create_index(
        "ix_workflows_status_updated", "workflows", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("actor_session_id", sa.String(length=36), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("workflow_id", sa.String(length=36), nullable=True),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column("plan_id", sa.String(length=36), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("operation_id", sa.String(length=36), nullable=True),
        sa.Column("message_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("authorization_decision", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.CheckConstraint("sequence >= 1", name=op.f("ck_audit_events_audit_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["actor_session_id"],
            ["login_sessions.id"],
            name=op.f("fk_audit_events_actor_session_id_login_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_audit_events_ticket_id_tickets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_audit_events_workflow_id_workflows"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("sequence", name=op.f("uq_audit_events_sequence")),
    )
    op.create_index(
        "ix_audit_events_actor_timeline",
        "audit_events",
        ["actor_user_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_resource_timeline",
        "audit_events",
        ["resource_type", "resource_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_ticket_timeline", "audit_events", ["ticket_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_audit_events_workflow_timeline",
        "audit_events",
        ["workflow_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "document_segments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.String(length=1000), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("source_anchor", sa.String(length=500), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "sequence >= 0", name=op.f("ck_document_segments_document_segment_sequence_nonnegative")
        ),
        sa.CheckConstraint(
            "token_count >= 0",
            name=op.f("ck_document_segments_document_segment_tokens_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_segments_document_version_id_document_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_segments")),
        sa.UniqueConstraint(
            "document_version_id", "sequence", name="uq_document_segments_version_sequence"
        ),
    )
    op.create_index(
        "ix_document_segments_active",
        "document_segments",
        ["document_version_id", "active"],
        unique=False,
    )
    op.create_table(
        "evaluation_results",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=255), nullable=False),
        sa.Column("expected_summary", sa.JSON(), nullable=False),
        sa.Column("actual_summary", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("error_category", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column("workflow_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_path", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["evaluation_runs.id"],
            name=op.f("fk_evaluation_results_run_id_evaluation_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_evaluation_results_workflow_id_workflows"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("run_id", "case_id", name=op.f("pk_evaluation_results")),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("source_message_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=True),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "EMAIL_SANDBOX",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("recipient_scope", sa.String(length=255), nullable=False),
        sa.Column("content_template", sa.String(length=128), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("template_data", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENDING",
                "DELIVERED",
                "RETRYING",
                "UNKNOWN",
                "FAILED",
                name="notification_delivery_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_key", sa.String(length=128), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_summary", sa.String(length=500), nullable=True),
        sa.Column("unknown_since", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name=op.f("ck_notification_deliveries_notification_attempt_nonnegative"),
        ),
        sa.CheckConstraint(
            "template_version >= 1",
            name=op.f("ck_notification_deliveries_notification_template_version_positive"),
        ),
        sa.CheckConstraint(
            "workflow_id IS NOT NULL OR ticket_id IS NOT NULL",
            name=op.f("ck_notification_deliveries_notification_has_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation_ledger.operation_id"],
            name=op.f("fk_notification_deliveries_operation_id_operation_ledger"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["outbox_events.message_id"],
            name=op.f("fk_notification_deliveries_source_message_id_outbox_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
            name=op.f("fk_notification_deliveries_ticket_id_tickets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_notification_deliveries_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_notification_deliveries_operation_id")),
    )
    op.create_index(
        "ix_notification_delivery_status_due",
        "notification_deliveries",
        ["status", "next_attempt_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_ticket",
        "notification_deliveries",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_workflow",
        "notification_deliveries",
        ["workflow_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "workflow_commands",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "USER_MESSAGE",
                "CLARIFICATION",
                "APPROVAL_RESUME",
                "CANCEL",
                "RECOVER",
                name="workflow_command_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("expected_workflow_version", sa.Integer(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "APPLIED",
                "REJECTED",
                "FAILED",
                name="workflow_command_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_workflow_commands_workflow_command_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_commands_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_commands")),
        sa.UniqueConstraint("workflow_id", "sequence", name="uq_workflow_commands_sequence"),
    )
    op.create_index(
        "ix_workflow_commands_pending", "workflow_commands", ["status", "created_at"], unique=False
    )
    op.create_table(
        "workflow_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("source_model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("normalized_request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "VALIDATED",
                "SUPERSEDED",
                "REJECTED",
                name="workflow_plan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="risk_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("validation_summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_workflow_plans_plan_schema_version_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workflow_plans_plan_version_positive")),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.id"], name="fk_plan_workflow", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_workflow_plans")),
        sa.UniqueConstraint("workflow_id", "version", name="uq_workflow_plans_workflow_version"),
    )
    op.create_table(
        "plan_tasks",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "KNOWLEDGE_QUERY",
                "TICKET_CREATE",
                "TICKET_QUERY",
                "TICKET_UPDATE",
                "NOTIFICATION_SEND",
                "OPS_ACTION",
                name="plan_task_intent",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_span", sa.Text(), nullable=False),
        sa.Column("slots", sa.JSON(), nullable=False),
        sa.Column("missing_slots", sa.JSON(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "CRITICAL",
                name="plan_task_risk_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("operation_id", sa.String(length=36), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_plan_tasks_plan_task_position_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version"],
            ["workflow_plans.id", "workflow_plans.version"],
            name="fk_plan_tasks_plan",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("plan_id", "plan_version", "id", name=op.f("pk_plan_tasks")),
        sa.UniqueConstraint("operation_id", name="uq_plan_tasks_operation_id"),
    )
    op.create_table(
        "retrieval_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("redacted_query", sa.String(length=1000), nullable=True),
        sa.Column("user_scope_hash", sa.String(length=64), nullable=False),
        sa.Column("acl_version", sa.Integer(), nullable=False),
        sa.Column("retrieval_config_version", sa.String(length=128), nullable=False),
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("dense_score", sa.Float(), nullable=True),
        sa.Column("bm25_score", sa.Float(), nullable=True),
        sa.Column("fused_score", sa.Float(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "`rank` >= 1", name=op.f("ck_retrieval_evidence_retrieval_rank_positive")
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["document_segments.id"],
            name=op.f("fk_retrieval_evidence_segment_id_document_segments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_retrieval_evidence_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_evidence")),
    )
    op.create_index(
        "ix_retrieval_evidence_segment",
        "retrieval_evidence",
        ["segment_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_retrieval_evidence_workflow",
        "retrieval_evidence",
        ["workflow_id", "task_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("normalized_parameters", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("requester_user_id", sa.String(length=36), nullable=False),
        sa.Column("approver_user_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                "INVALIDATED",
                name="approval_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "plan_version >= 1", name=op.f("ck_approvals_approval_plan_version_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_approvals_approval_version_positive")),
        sa.ForeignKeyConstraint(
            ["approver_user_id"],
            ["users.id"],
            name=op.f("fk_approvals_approver_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation_ledger.operation_id"],
            name=op.f("fk_approvals_operation_id_operation_ledger"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version", "task_id"],
            ["plan_tasks.plan_id", "plan_tasks.plan_version", "plan_tasks.id"],
            name="fk_approvals_task",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version"],
            ["workflow_plans.id", "workflow_plans.version"],
            name="fk_approvals_plan",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
            name=op.f("fk_approvals_requester_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_approvals_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index("ix_approvals_pending", "approvals", ["status", "expires_at"], unique=False)
    op.create_index(
        "ix_approvals_workflow", "approvals", ["workflow_id", "created_at"], unique=False
    )
    op.create_table(
        "plan_dependencies",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("plan_version", sa.Integer(), nullable=False),
        sa.Column("from_task_id", sa.String(length=36), nullable=False),
        sa.Column("to_task_id", sa.String(length=36), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "SEQUENCE",
                "DATA",
                "ON_SUCCESS",
                "ON_FAILURE",
                name="plan_dependency_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("output_binding", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "from_task_id <> to_task_id", name=op.f("ck_plan_dependencies_plan_dependency_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version", "from_task_id"],
            ["plan_tasks.plan_id", "plan_tasks.plan_version", "plan_tasks.id"],
            name="fk_plan_dependencies_from_task",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id", "plan_version", "to_task_id"],
            ["plan_tasks.plan_id", "plan_tasks.plan_version", "plan_tasks.id"],
            name="fk_plan_dependencies_to_task",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "plan_id",
            "plan_version",
            "from_task_id",
            "to_task_id",
            "kind",
            name=op.f("pk_plan_dependencies"),
        ),
    )
    # Deferred cycle edges are intentionally created after every referenced table exists.
    op.create_foreign_key(
        "fk_documents_active_version",
        "documents",
        "document_versions",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_workflows_current_plan",
        "workflows",
        "workflow_plans",
        ["plan_id", "plan_version"],
        ["id", "version"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_workflows_pending_approval",
        "workflows",
        "approvals",
        ["pending_approval_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # MySQL can select a user index to support a foreign key, which makes Alembic's generated
    # drop-index-before-drop-table sequence invalid. The initial revision contains no user data, so
    # drop its known tables with FK checks suspended and always restore the session setting.
    tables = (
        "plan_dependencies",
        "approvals",
        "retrieval_evidence",
        "plan_tasks",
        "workflow_plans",
        "workflow_commands",
        "notification_deliveries",
        "evaluation_results",
        "document_segments",
        "audit_events",
        "workflows",
        "ticket_events",
        "document_versions",
        "document_acl_grants",
        "user_roles",
        "tickets",
        "login_sessions",
        "documents",
        "users",
        "outbox_events",
        "teams",
        "roles",
        "operation_ledger",
        "inbox_messages",
        "evaluation_runs",
    )
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    try:
        for table in tables:
            op.drop_table(table)
    finally:
        op.execute("SET FOREIGN_KEY_CHECKS=1")
    return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_dependencies")
    op.drop_index("ix_approvals_workflow", table_name="approvals")
    op.drop_index("ix_approvals_pending", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_retrieval_evidence_workflow", table_name="retrieval_evidence")
    op.drop_index("ix_retrieval_evidence_segment", table_name="retrieval_evidence")
    op.drop_table("retrieval_evidence")
    op.drop_table("plan_tasks")
    op.drop_table("workflow_plans")
    op.drop_index("ix_workflow_commands_pending", table_name="workflow_commands")
    op.drop_table("workflow_commands")
    op.drop_index("ix_notification_workflow", table_name="notification_deliveries")
    op.drop_index("ix_notification_ticket", table_name="notification_deliveries")
    op.drop_index("ix_notification_delivery_status_due", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("evaluation_results")
    op.drop_index("ix_document_segments_active", table_name="document_segments")
    op.drop_table("document_segments")
    op.drop_index("ix_audit_events_workflow_timeline", table_name="audit_events")
    op.drop_index("ix_audit_events_ticket_timeline", table_name="audit_events")
    op.drop_index("ix_audit_events_resource_timeline", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_timeline", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_workflows_status_updated", table_name="workflows")
    op.drop_index("ix_workflows_owner_status", table_name="workflows")
    op.drop_table("workflows")
    op.drop_index("ix_ticket_events_timeline", table_name="ticket_events")
    op.drop_table("ticket_events")
    op.drop_index("ix_document_versions_status", table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index("ix_document_acl_principal", table_name="document_acl_grants")
    op.drop_table("document_acl_grants")
    op.drop_table("user_roles")
    op.drop_index("ix_tickets_team_status", table_name="tickets")
    op.drop_index("ix_tickets_sla_due", table_name="tickets")
    op.drop_index("ix_tickets_creator_status", table_name="tickets")
    op.drop_table("tickets")
    op.drop_index("ix_login_sessions_user_status", table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_token_family_id"), table_name="login_sessions")
    op.drop_index("ix_login_sessions_expiry", table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_index("ix_documents_scope_status", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_users_team_status", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_outbox_due", table_name="outbox_events")
    op.drop_index("ix_outbox_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_table("teams")
    op.drop_table("roles")
    op.drop_index("ix_operation_ledger_status_lease", table_name="operation_ledger")
    op.drop_table("operation_ledger")
    op.drop_index("ix_inbox_processing", table_name="inbox_messages")
    op.drop_table("inbox_messages")
    op.drop_index("ix_evaluation_runs_suite_started", table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    # ### end Alembic commands ###
